networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: library
    ports:
      - 3306:3306
    volumes:
      - "./.data/library:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: library_db
  db_airport:
    image: mysql:8.0
    container_name: airport
    ports:
      - 33061:3306
    volumes:
      - "./.data/airport:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: airport_db
  db_person:
    image: mysql:8.0
    container_name: person
    ports:
      - 33062:3306
    volumes:
      - "./.data/person:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: person_db
